repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
